<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RiverSeeder extends Seeder
{
    public function run(): void
    {
        $rivers = [
            [
                'uid' => 'bagmati',
                'name' => 'Bagmati River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 597,
                'water_level_current' => 2.3,
                'water_level_normal' => 2.0,
                'water_level_status' => 'normal',
                'flow_rate_current' => 120,
                'flow_rate_average' => 110,
                'temperature' => 18,
                'lat' => 27.6878,
                'lng' => 85.3386,
                'description' => 'The main river of the Kathmandu Valley, considered sacred in Hinduism and central to the valley’s drainage system.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 2.0, 'flow' => 110],
                    ['day' => 'Tue', 'level' => 2.1, 'flow' => 115],
                    ['day' => 'Wed', 'level' => 2.2, 'flow' => 118],
                    ['day' => 'Thu', 'level' => 2.3, 'flow' => 120],
                    ['day' => 'Fri', 'level' => 2.2, 'flow' => 115],
                    ['day' => 'Sat', 'level' => 2.1, 'flow' => 112],
                    ['day' => 'Sun', 'level' => 2.3, 'flow' => 120],
                ]),
            ],
            [
                'uid' => 'bishnumati',
                'name' => 'Bishnumati River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 25,
                'water_level_current' => 1.4,
                'water_level_normal' => 1.6,
                'water_level_status' => 'low',
                'flow_rate_current' => 80,
                'flow_rate_average' => 90,
                'temperature' => 18,
                'lat' => 27.7222,
                'lng' => 85.3131,
                'description' => 'A tributary of the Bagmati River flowing through Kathmandu, historically important for settlements and temples.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 1.6, 'flow' => 90],
                    ['day' => 'Tue', 'level' => 1.5, 'flow' => 85],
                    ['day' => 'Wed', 'level' => 1.4, 'flow' => 82],
                    ['day' => 'Thu', 'level' => 1.4, 'flow' => 80],
                    ['day' => 'Fri', 'level' => 1.3, 'flow' => 78],
                    ['day' => 'Sat', 'level' => 1.4, 'flow' => 80],
                    ['day' => 'Sun', 'level' => 1.4, 'flow' => 80],
                ]),
            ],
            [
                'uid' => 'manohara',
                'name' => 'Manohara River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 20,
                'water_level_current' => 2.8,
                'water_level_normal' => 2.5,
                'water_level_status' => 'high',
                'flow_rate_current' => 140,
                'flow_rate_average' => 120,
                'temperature' => 17,
                'lat' => 27.6780,
                'lng' => 85.3906,
                'description' => 'An important tributary of the Bagmati River, originating from Nagarkot and flowing through Bhaktapur.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 2.5, 'flow' => 120],
                    ['day' => 'Tue', 'level' => 2.6, 'flow' => 125],
                    ['day' => 'Wed', 'level' => 2.7, 'flow' => 130],
                    ['day' => 'Thu', 'level' => 2.8, 'flow' => 140],
                    ['day' => 'Fri', 'level' => 2.7, 'flow' => 135],
                    ['day' => 'Sat', 'level' => 2.6, 'flow' => 128],
                    ['day' => 'Sun', 'level' => 2.8, 'flow' => 140],
                ]),
            ],
            [
                'uid' => 'hanumante',
                'name' => 'Hanumante River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 12,
                'water_level_current' => 1.9,
                'water_level_normal' => 2.0,
                'water_level_status' => 'normal',
                'flow_rate_current' => 60,
                'flow_rate_average' => 65,
                'temperature' => 17,
                'lat' => 27.6715,
                'lng' => 85.4273,
                'description' => 'Flows through Bhaktapur before joining the Manohara River; often floods during monsoon.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 2.0, 'flow' => 65],
                    ['day' => 'Tue', 'level' => 1.9, 'flow' => 63],
                    ['day' => 'Wed', 'level' => 1.8, 'flow' => 60],
                    ['day' => 'Thu', 'level' => 1.9, 'flow' => 60],
                    ['day' => 'Fri', 'level' => 1.9, 'flow' => 61],
                    ['day' => 'Sat', 'level' => 1.8, 'flow' => 59],
                    ['day' => 'Sun', 'level' => 1.9, 'flow' => 60],
                ]),
            ],
            [
                'uid' => 'dhobi-khola',
                'name' => 'Dhobi Khola',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 18,
                'water_level_current' => 1.5,
                'water_level_normal' => 1.7,
                'water_level_status' => 'low',
                'flow_rate_current' => 55,
                'flow_rate_average' => 65,
                'temperature' => 17,
                'lat' => 27.7022,
                'lng' => 85.3472,
                'description' => 'Flows through eastern Kathmandu before joining the Bagmati River near Bijuli Bazaar.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 1.7, 'flow' => 65],
                    ['day' => 'Tue', 'level' => 1.6, 'flow' => 60],
                    ['day' => 'Wed', 'level' => 1.5, 'flow' => 58],
                    ['day' => 'Thu', 'level' => 1.5, 'flow' => 55],
                    ['day' => 'Fri', 'level' => 1.4, 'flow' => 53],
                    ['day' => 'Sat', 'level' => 1.5, 'flow' => 55],
                    ['day' => 'Sun', 'level' => 1.5, 'flow' => 55],
                ]),
            ],
            [
                'uid' => 'tukucha',
                'name' => 'Tukucha River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 10,
                'water_level_current' => 1.2,
                'water_level_normal' => 1.5,
                'water_level_status' => 'low',
                'flow_rate_current' => 40,
                'flow_rate_average' => 50,
                'temperature' => 17,
                'lat' => 27.7146,
                'lng' => 85.3167,
                'description' => 'A small river in Kathmandu, much of it has been diverted underground.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 1.5, 'flow' => 50],
                    ['day' => 'Tue', 'level' => 1.4, 'flow' => 48],
                    ['day' => 'Wed', 'level' => 1.3, 'flow' => 45],
                    ['day' => 'Thu', 'level' => 1.2, 'flow' => 40],
                    ['day' => 'Fri', 'level' => 1.2, 'flow' => 42],
                    ['day' => 'Sat', 'level' => 1.3, 'flow' => 44],
                    ['day' => 'Sun', 'level' => 1.2, 'flow' => 40],
                ]),
            ],
            [
                'uid' => 'godavari',
                'name' => 'Godavari River',
                'country' => 'Nepal',
                'continent' => 'Asia',
                'length' => 15,
                'water_level_current' => 1.8,
                'water_level_normal' => 1.9,
                'water_level_status' => 'normal',
                'flow_rate_current' => 70,
                'flow_rate_average' => 75,
                'temperature' => 16,
                'lat' => 27.5903,
                'lng' => 85.3919,
                'description' => 'Originates from the Godavari Kunda in Lalitpur; known for religious and cultural significance.',
                'last_updated' => now(),
                'weekly_data' => json_encode([
                    ['day' => 'Mon', 'level' => 1.9, 'flow' => 75],
                    ['day' => 'Tue', 'level' => 1.8, 'flow' => 72],
                    ['day' => 'Wed', 'level' => 1.7, 'flow' => 70],
                    ['day' => 'Thu', 'level' => 1.8, 'flow' => 70],
                    ['day' => 'Fri', 'level' => 1.8, 'flow' => 71],
                    ['day' => 'Sat', 'level' => 1.7, 'flow' => 69],
                    ['day' => 'Sun', 'level' => 1.8, 'flow' => 70],
                ]),
            ],
        ];

        DB::table('rivers')->upsert($rivers, ['uid']);
    }
}
